### ISSUE TITLE
JavaScript Track Courses to be completed

### ISSUE THREAD

**Issue by lifelearner2** [lifelearner2/Treehouse#2]
## TODO

*Courses left to complete the Treehouse JavaScript Track*

- [x] JS Sample Basics
- [x] JS Sample Course
- [x] Object Oriented Programming

:tada :ok_woman: 🎊  :black_heart:

cc @lifelearner2
